const STORAGE_KEY = 'action-score-pwa-v1';
const CATEGORIES = ['高等级', '中等级', '低等级'];
const LEVELS = ['A', 'B', 'C'];
const DEFAULT_SCORES = { 高等级: { A: 10, B: 7, C: 5 }, 中等级: { A: 4, B: 3, C: 2 }, 低等级: { A: -3, B: -5, C: -10 } };
const INITIAL = {
  高等级: { A: ['专业领域的学习', '高投入的工作', '技能训练', '创造个人作品'], B: ['中高等负荷的运动健身', '写论文/读文献', '技能兴趣（绘画/手工等）', '处理拖延的事项'], C: ['深度连接的社交', '旅行/户外探索', '沉浸式阅读', '学习/背单词'] },
  中等级: { A: ['处理工作任务', '规律起居和饮食', '瑜伽/冥想', '跑步/其他运动'], B: ['阅读', '扫地/拖地/整理/洗衣服', '做想吃的饭', '陌生人社交（剧本杀等）'], C: ['沉浸式观影', '洗澡/清洁', '与熟人见面', '去外面吃饭'] },
  低等级: { A: ['长时间刷信息流', '无休息体验的躺平', '非饥饿状态下的频繁饮食', '困倦下的熬夜'], B: ['频繁的自慰', '无节制的性行为', '严重的成瘾行为', '强迫性购物'], C: ['冲动行为', '药物滥用', '自残', '毒品'] }
};
const initialState = () => ({ version: 1, activities: CATEGORIES.flatMap(category => LEVELS.flatMap(level => INITIAL[category][level].map(name => ({ id: crypto.randomUUID(), name, category, level, score: DEFAULT_SCORES[category][level], enabled: true })))), logs: [], defaults: structuredClone(DEFAULT_SCORES), grades: [{ label: 'S', min: 100 }, { label: 'A', min: 80 }, { label: 'B', min: 60 }, { label: 'C', min: 40 }, { label: 'D', min: 0 }, { label: 'E', min: -Infinity }] });
let state = load(); let page = 'today'; let feedbackTimer;
const $ = selector => document.querySelector(selector);
function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.activities && saved?.logs ? saved : initialState(); } catch { return initialState(); } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function dayKey(date = new Date()) { const d = new Date(date); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function logsForDay(key) { return state.logs.filter(log => log.day === key).sort((a,b) => new Date(b.at) - new Date(a.at)); }
function daySummary(key) { const logs = logsForDay(key); const totals = Object.fromEntries(CATEGORIES.map(c => [c, logs.filter(l => l.category === c).reduce((sum,l) => sum + l.score, 0)])); return { logs, totals, score: logs.reduce((sum, log) => sum + log.score, 0) }; }
function gradeFor(score) { return state.grades.slice().sort((a,b) => b.min-a.min).find(rule => score >= rule.min)?.label ?? 'E'; }
function signed(value) { return `${value > 0 ? '+' : ''}${value}`; }
function dateText(key) { const [year,month,day] = key.split('-').map(Number); return `${month}月${day}日`; }
function timeText(at) { return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(at)); }
function categoryClass(category) { return category === '高等级' ? 'high' : category === '中等级' ? 'mid' : 'low'; }
function getActivity(id) { return state.activities.find(activity => activity.id === id); }
function updateActivityScore(activity) { activity.score = state.defaults[activity.category][activity.level]; }

function render() { $('#app').innerHTML = `<div class="app">${page === 'today' ? todayView() : page === 'history' ? historyView() : settingsView()}</div>${navView()}`; bind(); }
function navView() { return `<nav class="nav"><div class="nav-inner">${[['today','今天'],['history','历史'],['settings','设置']].map(([id,label]) => `<button class="${page===id?'active':''}" data-page="${id}">${label}</button>`).join('')}</div></nav>`; }
function todayView() { const summary = daySummary(dayKey()); const counts = Object.fromEntries(summary.logs.map(l => [l.activityId, (summary.logs.filter(x => x.activityId === l.activityId).length)])); return `<header class="topbar"><div><div class="eyebrow">${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</div><h1>今天</h1></div>${summary.logs.length ? '<button class="undo" id="undo">撤销最近一次</button>' : ''}</header><section class="today-card"><div class="score-label">今日行动分</div><div class="score" id="score">${summary.score}</div><div class="grade">行动等级：<strong>${gradeFor(summary.score)}</strong></div><div class="breakdown"><div>高等级<strong>${signed(summary.totals.高等级)}</strong></div><div>中等级<strong>${signed(summary.totals.中等级)}</strong></div><div>低等级<strong>${signed(summary.totals.低等级)}</strong></div><div>记录次数<strong>${summary.logs.length}</strong></div></div></section><section class="section"><div class="section-head"><h2>快速记录</h2><span class="hint">点一下即记录</span></div>${CATEGORIES.map(category => activityGroup(category, counts)).join('')}</section><section class="section"><div class="section-head"><h2>今日记录</h2><span class="hint">最新在前</span></div>${timeline(summary.logs)}</section>`; }
function activityGroup(category, counts={}) { const activities = state.activities.filter(a => a.enabled && a.category === category); return `<div class="group"><h3 class="group-title ${categoryClass(category)}">${category}<span>${category === '高等级'?'主动意志和觉知':category === '中等级'?'被动但不失调':'被动、反射、失调'}</span></h3><div class="activity-grid">${activities.map(a => `<button class="activity ${categoryClass(category)}" data-log="${a.id}"><span class="activity-name">${escapeHtml(a.name)}${counts[a.id] ? ` <small>×${counts[a.id]}</small>` : ''}</span><span class="activity-score">${signed(a.score)}</span></button>`).join('') || '<span class="empty">暂无启用的行为</span>'}</div></div>`; }
function timeline(logs) { return logs.length ? `<div class="timeline">${logs.map(log => `<div class="log"><time>${timeText(log.at)}</time><span>${escapeHtml(log.name)}</span><strong class="log-value ${log.score >= 0 ? 'positive':'negative'}">${signed(log.score)}</strong></div>`).join('')}</div>` : '<p class="empty">还没有记录。完成一件事后，点一下上面的行为。</p>'; }
function recentDays(days=30) { return Array.from({length:days},(_,index) => { const d=new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate()-index); return dayKey(d); }); }
function historyView() { const days=recentDays(30); const entries=days.map(key => ({key,...daySummary(key)})); const scored=entries.filter(x=>x.logs.length); const avg = n => { const items=entries.slice(0,n).filter(x=>x.logs.length); return items.length ? Math.round(items.reduce((sum,x)=>sum+x.score,0)/items.length) : 0; }; const allLogs=entries.slice(0,7).flatMap(x=>x.logs); const counts=Object.fromEntries(CATEGORIES.map(c=>[c,allLogs.filter(l=>l.category===c).length])); const values=scored.map(x=>x.score); return `<header class="topbar"><div><div class="eyebrow">最近 30 天</div><h1>历史</h1></div></header><div class="stat-grid"><div class="stat"><label>今日分数</label><strong>${entries[0].score}</strong></div><div class="stat"><label>近 7 日平均</label><strong>${avg(7)}</strong></div><div class="stat"><label>近 30 日平均</label><strong>${avg(30)}</strong></div><div class="stat"><label>最高 / 最低</label><strong>${values.length ? `${Math.max(...values)} / ${Math.min(...values)}` : '—'}</strong></div></div><section class="chart"><div class="section-head"><h2>每日行动分</h2><span class="hint">近 30 天</span></div>${chart(entries.slice().reverse())}</section><section class="section"><div class="section-head"><h2>最近 7 天行为结构</h2></div><div class="stat-grid"><div class="stat"><label>高等级</label><strong class="high">${counts.高等级}</strong></div><div class="stat"><label>中等级</label><strong class="mid">${counts.中等级}</strong></div><div class="stat"><label>低等级</label><strong class="low">${counts.低等级}</strong></div></div></section><section class="section"><div class="section-head"><h2>每日记录</h2><span class="hint">点击查看明细</span></div><div class="history-list">${scored.map(item=>`<button class="day-row" data-day="${item.key}"><span>${dateText(item.key)}</span><strong>${item.score}</strong><span class="pill">${gradeFor(item.score)}</span></button>`).join('') || '<p class="empty">最近 30 天还没有记录。</p>'}</div></section>`; }
function chart(entries) { const values=entries.map(x=>x.score); const min=Math.min(0,...values),max=Math.max(10,...values), range=max-min||1; const points=values.map((value,index)=>`${index/(values.length-1)*100},${100-(value-min)/range*88}`).join(' '); return `<svg viewBox="0 0 100 112" preserveAspectRatio="none" aria-label="每日分数折线图"><line x1="0" y1="100" x2="100" y2="100" stroke="#dedfd8" vector-effect="non-scaling-stroke"/><line x1="0" y1="${100-(0-min)/range*88}" x2="100" y2="${100-(0-min)/range*88}" stroke="#dedfd8" stroke-dasharray="3" vector-effect="non-scaling-stroke"/><polyline points="${points}" fill="none" stroke="#315b45" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linejoin="round"/><text x="0" y="110">${dateText(entries[0].key)}</text><text x="84" y="110">${dateText(entries.at(-1).key)}</text><text x="1" y="10">${max}</text><text x="1" y="98">${min}</text></svg>`; }
function settingsView() { return `<header class="topbar"><div><div class="eyebrow">个人配置</div><h1>设置</h1></div></header><section class="settings-card"><h2>默认分值</h2><p>用于新增行为，以及你选择“使用默认分值”的行为。编辑某个具体行为时可保留独立分值；已记录的历史不会改变。</p>${CATEGORIES.map(category=>`<h3 class="group-title ${categoryClass(category)}">${category}</h3><div class="defaults">${LEVELS.map(level=>`<div class="default-cell"><label>${level} 等级</label><input type="number" data-default="${category}|${level}" value="${state.defaults[category][level]}"></div>`).join('')}</div>`).join('')}<div class="settings-actions"><button class="button" id="save-defaults">保存默认分值</button></div></section><section class="settings-card"><h2>每日行动等级</h2><p>每个等级填写达到该等级所需的最低分数。系统按分数从高到低判定。</p><div class="defaults">${state.grades.filter(g=>Number.isFinite(g.min)).map(g=>`<div class="default-cell"><label>${g.label}</label><input type="number" data-grade="${g.label}" value="${g.min}"></div>`).join('')}</div><div class="settings-actions"><button class="button" id="save-grades">保存等级区间</button></div></section><section class="settings-card"><div class="section-head"><h2>行为设置</h2><button class="button" id="add-activity">新增行为</button></div><p>具体行为分值可独立修改；分类或 A/B/C 改变后可一键套用新的默认分值。</p>${state.activities.map(activitySetting).join('')}</section><section class="settings-card"><h2>数据</h2><p>导出包含行为、评分规则和全部历史记录。导入会覆盖当前本地数据。</p><div class="settings-actions"><button class="button secondary" id="export">导出 JSON</button><button class="button secondary" id="import">导入 JSON</button></div></section><section class="settings-card"><h2>说明</h2><p>行动分用于记录和观察个人行为结构，不代表客观能力或心理状态。</p></section>`; }
function activitySetting(a) { return `<details class="activity-setting"><summary><span>${escapeHtml(a.name)} <small class="${categoryClass(a.category)}">${a.category} · ${a.level}</small></span><strong>${signed(a.score)}</strong></summary><form class="edit-form" data-edit="${a.id}"><input class="wide" name="name" value="${escapeHtml(a.name)}" required><select name="category">${CATEGORIES.map(c=>`<option ${c===a.category?'selected':''}>${c}</option>`).join('')}</select><select name="level">${LEVELS.map(l=>`<option ${l===a.level?'selected':''}>${l}</option>`).join('')}</select><input name="score" type="number" value="${a.score}" required><label class="toggle"><input name="enabled" type="checkbox" ${a.enabled?'checked':''}> 启用</label><label class="toggle wide"><input name="useDefault" type="checkbox"> 套用所选分类与等级的默认分值</label><button class="button" type="submit">保存</button><button class="button danger" type="button" data-delete="${a.id}">删除</button></form></details>`; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function bind() { document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{page=button.dataset.page;render();}); document.querySelectorAll('[data-log]').forEach(button=>button.onclick=()=>logActivity(button.dataset.log)); $('#undo')?.addEventListener('click', undo); document.querySelectorAll('[data-day]').forEach(button=>button.onclick=()=>showDay(button.dataset.day)); $('#save-defaults')?.addEventListener('click',saveDefaults); $('#save-grades')?.addEventListener('click',saveGrades); $('#add-activity')?.addEventListener('click',showAdd); $('#export')?.addEventListener('click',exportData); $('#import')?.addEventListener('click',()=>$('#import-file').click()); document.querySelectorAll('[data-edit]').forEach(form=>form.addEventListener('submit',saveActivity)); document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>deleteActivity(button.dataset.delete)); }
function logActivity(id) { const a=getActivity(id); if(!a) return; const at=new Date(); state.logs.push({id:crypto.randomUUID(),activityId:a.id,name:a.name,category:a.category,level:a.level,score:Number(a.score),at:at.toISOString(),day:dayKey(at)}); save(); render(); showFeedback(a); }
function showFeedback(a) { clearTimeout(feedbackTimer); document.querySelector('.feedback')?.remove(); const el=document.createElement('div'); el.className='feedback'; el.innerHTML=`<strong>${signed(a.score)}</strong><small>${escapeHtml(a.name)} ×${logsForDay(dayKey()).filter(l=>l.activityId===a.id).length}</small>`; document.body.append(el); feedbackTimer=setTimeout(()=>el.remove(),900); }
function undo() { const today=dayKey(); const latest=logsForDay(today)[0]; if(!latest)return; state.logs=state.logs.filter(log=>log.id!==latest.id); save(); render(); }
function showDay(key) { const summary=daySummary(key); const dialog=document.createElement('div'); dialog.className='dialog'; dialog.innerHTML=`<div class="dialog-box"><button class="dialog-close">×</button><h2>${dateText(key)}</h2><div class="detail-summary">行动分 ${summary.score} · 行动等级 ${gradeFor(summary.score)} · ${summary.logs.length} 条记录</div>${timeline(summary.logs)}</div>`; document.body.append(dialog); dialog.addEventListener('click',event=>{if(event.target===dialog||event.target.matches('.dialog-close'))dialog.remove();}); }
function saveDefaults() { document.querySelectorAll('[data-default]').forEach(input=>{const [category,level]=input.dataset.default.split('|'); state.defaults[category][level]=Number(input.value);}); save(); render(); }
function saveGrades() { const values=Array.from(document.querySelectorAll('[data-grade]')).map(input=>({label:input.dataset.grade,min:Number(input.value)})); if(new Set(values.map(x=>x.min)).size!==values.length){alert('每个等级的最低分数需要不同。');return;} state.grades=[...values,{label:'E',min:-Infinity}]; save(); render(); }
function saveActivity(event) { event.preventDefault(); const form=event.currentTarget,a=getActivity(form.dataset.edit),data=new FormData(form); a.name=data.get('name').trim(); a.category=data.get('category'); a.level=data.get('level'); a.score=data.has('useDefault')?state.defaults[a.category][a.level]:Number(data.get('score')); a.enabled=data.has('enabled'); save(); render(); }
function deleteActivity(id) { const a=getActivity(id); if(a && confirm(`删除“${a.name}”？历史记录会保留。`)){state.activities=state.activities.filter(x=>x.id!==id);save();render();} }
function showAdd() { const dialog=document.createElement('div');dialog.className='dialog';dialog.innerHTML=`<div class="dialog-box"><button class="dialog-close">×</button><h2>新增行为</h2><p class="detail-summary">保存后会立即显示在“今天”。</p><form class="edit-form" id="new-form"><input class="wide" name="name" placeholder="行为名称" required autofocus><select name="category">${CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select><select name="level">${LEVELS.map(l=>`<option>${l}</option>`).join('')}</select><input name="score" type="number" value="10" required><label class="toggle"><input name="useDefault" type="checkbox"> 使用默认分值</label><button class="button wide">保存行为</button></form></div>`;document.body.append(dialog);dialog.addEventListener('click',event=>{if(event.target===dialog||event.target.matches('.dialog-close'))dialog.remove();});$('#new-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget),category=data.get('category'),level=data.get('level');state.activities.push({id:crypto.randomUUID(),name:data.get('name').trim(),category,level,score:data.has('useDefault')?state.defaults[category][level]:Number(data.get('score')),enabled:true});save();dialog.remove();render();}); }
function exportData() { const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`行动积分器-${dayKey()}.json`;link.click();URL.revokeObjectURL(url); }
$('#import-file').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!Array.isArray(imported.activities)||!Array.isArray(imported.logs)||!imported.defaults||!imported.grades)throw new Error();if(confirm('导入将覆盖当前本地数据，是否继续？')){state=imported;save();render();}}catch{alert('这不是可用的行动积分器备份文件。');}event.target.value='';};reader.readAsText(file);});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
